spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/minikode?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '!biobio3730@'

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDB103Dialect
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false