spring:
  config:
    import: "optional:configserver:http://localhost:8090"
  cloud:
    config:
      name: api
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 5
        multiplier: 1.1
      request-connect-timeout: 2000
      request-read-timeout: 10000
      uri: http://localhost:8090

management:
  endpoints:
    web:
      exposure:
        include: [ "env", "refresh" ]

#logging:
#  level:
#    root: INFO
#    com.minikode: DEBUG
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
#logging:
#  level:
#    root: INFO
